extends Node

var mainCurses = [
	{"Name":"Curse of Gambling",
	"ID":"gambling",
	"Icon":"res://assets/images/ui/curses/gambling.png",
	"Known":false},
	{"Name":"Curse of Kindness",
	"ID":"kindness",
	"Icon":"res://assets/images/ui/curses/kindness.png",
	"Known":false},
	{"Name":"Curse of Mobile Game",
	"ID":"mobilegame",
	"Icon":"res://assets/images/ui/curses/ads.png",
	"Known":false},
	{"Name":"Curse of Pet Allergies",
	"ID":"jelly",
	"Icon":"res://assets/images/ui/curses/jelly.png",
	"Known":false},
	{"Name":"Curse of Black Lung",
	"ID":"blacklung",
	"Icon":"res://assets/images/ui/curses/blacklung.png",
	"Known":false},
	]
var passiveCurses = [
	{"Name":"Curse of Lost Bank Account",
	"ID":"bankaccount",
	"Icon":"res://assets/images/ui/curses/nobankaccount.png",
	"Known":false},
	{"Name":"Curse of Smoke Break",
	"ID":"smokebreak",
	"Icon":"res://assets/images/ui/curses/smokebreak.png",
	"Known":false},
	{"Name":"Curse of Quicktime",
	"ID":"quicktime",
	"Icon":"res://assets/images/ui/curses/quicktime.png",
	"Known":false},
	{"Name":"Curse of Taxes",
	"ID":"taxes",
	"Icon":"res://assets/images/ui/curses/taxes.png",
	"Known":false},
	{"Name":"Curse of Unpaid Labour",
	"ID":"unpaidlabour",
	"Icon":"res://assets/images/ui/curses/unpaidlabour.png",
	"Known":false},
	{"Name":"Curse of Capitalism",
	"ID":"capitalism",
	"Icon":"res://assets/images/ui/curses/capitalism.png",
	"Known":false},
	{"Name":"Curse of Senselessness",
	"ID":"senselessness",
	"Icon":"res://assets/images/ui/curses/senselessness.png",
	"Known":false},
	]

var curses = []

var spiceLevel = 1
